import {
  REQUEST_SCHEMAS,
  RESPONSE_SCHEMAS,
  EVENT_SCHEMAS,
  YOUTUBE_MANAGER_API_CONTRACT,
} from '../../shared/youtube-manager-contract.js'

/**
 * IPC Channel Contract
 *
 * Defines every allowed channel between the renderer and main processes.
 * No channel outside this list is registered in the main process, so
 * arbitrary ipcRenderer.invoke / ipcRenderer.send calls from the renderer
 * will simply receive no response.
 *
 * Channel naming convention:  domain:action
 *
 * INVOKE_CHANNELS  — request/response patterns (ipcRenderer.invoke)
 * EVENT_CHANNELS   — one-way push from main → renderer (webContents.send)
 */

// ---------------------------------------------------------------------------
// Channel name constants
// ---------------------------------------------------------------------------

export const CHANNELS = {
  // App utility
  APP_PING: 'app:ping',
  APP_GET_VERSION: 'app:get-version',

  // Auth / OAuth
  AUTH_IMPORT_CREDENTIALS: 'auth:import-credentials',
  AUTH_START_OAUTH: 'auth:start-oauth',
  AUTH_GET_STATUS: 'auth:get-status',
  AUTH_SIGN_OUT: 'auth:sign-out',

  // Channel info
  CHANNEL_GET_INFO: 'channel:get-info',

  // Queue management
  QUEUE_LIST: 'queue:list',
  QUEUE_ADD: 'queue:add',
  QUEUE_REMOVE: 'queue:remove',
  QUEUE_REORDER: 'queue:reorder',
  QUEUE_UPDATE: 'queue:update',

  // Upload control
  UPLOAD_START: 'upload:start',
  UPLOAD_PAUSE: 'upload:pause',
  UPLOAD_RESUME: 'upload:resume',
  UPLOAD_CANCEL: 'upload:cancel',

  // Metadata lookups
  METADATA_GET_CATEGORIES: 'metadata:get-categories',
  METADATA_GET_PLAYLISTS: 'metadata:get-playlists',

  // Push events: main → renderer  (not invocable)
  UPLOAD_PROGRESS: 'upload:progress',
  UPLOAD_STATUS_CHANGED: 'upload:status-changed',
}

// ---------------------------------------------------------------------------
// Channel sets
// ---------------------------------------------------------------------------

export const INVOKE_CHANNELS = new Set([
  CHANNELS.APP_PING,
  CHANNELS.APP_GET_VERSION,
  CHANNELS.AUTH_IMPORT_CREDENTIALS,
  CHANNELS.AUTH_START_OAUTH,
  CHANNELS.AUTH_GET_STATUS,
  CHANNELS.AUTH_SIGN_OUT,
  CHANNELS.CHANNEL_GET_INFO,
  CHANNELS.QUEUE_LIST,
  CHANNELS.QUEUE_ADD,
  CHANNELS.QUEUE_REMOVE,
  CHANNELS.QUEUE_REORDER,
  CHANNELS.QUEUE_UPDATE,
  CHANNELS.UPLOAD_START,
  CHANNELS.UPLOAD_PAUSE,
  CHANNELS.UPLOAD_RESUME,
  CHANNELS.UPLOAD_CANCEL,
  CHANNELS.METADATA_GET_CATEGORIES,
  CHANNELS.METADATA_GET_PLAYLISTS,
])

export const EVENT_CHANNELS = new Set([
  CHANNELS.UPLOAD_PROGRESS,
  CHANNELS.UPLOAD_STATUS_CHANGED,
])

// ---------------------------------------------------------------------------
// Zod schema maps
// ---------------------------------------------------------------------------

export const CHANNEL_REQUEST_SCHEMAS = {
  [CHANNELS.APP_PING]: REQUEST_SCHEMAS.APP_PING,
  [CHANNELS.APP_GET_VERSION]: REQUEST_SCHEMAS.APP_GET_VERSION,
  [CHANNELS.AUTH_IMPORT_CREDENTIALS]: REQUEST_SCHEMAS.AUTH_IMPORT_CREDENTIALS,
  [CHANNELS.AUTH_START_OAUTH]: REQUEST_SCHEMAS.AUTH_START_OAUTH,
  [CHANNELS.AUTH_GET_STATUS]: REQUEST_SCHEMAS.AUTH_GET_STATUS,
  [CHANNELS.AUTH_SIGN_OUT]: REQUEST_SCHEMAS.AUTH_SIGN_OUT,
  [CHANNELS.CHANNEL_GET_INFO]: REQUEST_SCHEMAS.CHANNEL_GET_INFO,
  [CHANNELS.QUEUE_LIST]: REQUEST_SCHEMAS.QUEUE_LIST,
  [CHANNELS.QUEUE_ADD]: REQUEST_SCHEMAS.QUEUE_ADD,
  [CHANNELS.QUEUE_REMOVE]: REQUEST_SCHEMAS.QUEUE_REMOVE,
  [CHANNELS.QUEUE_REORDER]: REQUEST_SCHEMAS.QUEUE_REORDER,
  [CHANNELS.QUEUE_UPDATE]: REQUEST_SCHEMAS.QUEUE_UPDATE,
  [CHANNELS.UPLOAD_START]: REQUEST_SCHEMAS.UPLOAD_START,
  [CHANNELS.UPLOAD_PAUSE]: REQUEST_SCHEMAS.UPLOAD_PAUSE,
  [CHANNELS.UPLOAD_RESUME]: REQUEST_SCHEMAS.UPLOAD_RESUME,
  [CHANNELS.UPLOAD_CANCEL]: REQUEST_SCHEMAS.UPLOAD_CANCEL,
  [CHANNELS.METADATA_GET_CATEGORIES]: REQUEST_SCHEMAS.METADATA_GET_CATEGORIES,
  [CHANNELS.METADATA_GET_PLAYLISTS]: REQUEST_SCHEMAS.METADATA_GET_PLAYLISTS,
}

export const CHANNEL_RESPONSE_SCHEMAS = {
  [CHANNELS.APP_PING]: RESPONSE_SCHEMAS.APP_PING,
  [CHANNELS.APP_GET_VERSION]: RESPONSE_SCHEMAS.APP_GET_VERSION,
  [CHANNELS.AUTH_IMPORT_CREDENTIALS]: RESPONSE_SCHEMAS.AUTH_IMPORT_CREDENTIALS,
  [CHANNELS.AUTH_START_OAUTH]: RESPONSE_SCHEMAS.AUTH_START_OAUTH,
  [CHANNELS.AUTH_GET_STATUS]: RESPONSE_SCHEMAS.AUTH_GET_STATUS,
  [CHANNELS.AUTH_SIGN_OUT]: RESPONSE_SCHEMAS.AUTH_SIGN_OUT,
  [CHANNELS.CHANNEL_GET_INFO]: RESPONSE_SCHEMAS.CHANNEL_GET_INFO,
  [CHANNELS.QUEUE_LIST]: RESPONSE_SCHEMAS.QUEUE_LIST,
  [CHANNELS.QUEUE_ADD]: RESPONSE_SCHEMAS.QUEUE_ADD,
  [CHANNELS.QUEUE_REMOVE]: RESPONSE_SCHEMAS.QUEUE_REMOVE,
  [CHANNELS.QUEUE_REORDER]: RESPONSE_SCHEMAS.QUEUE_REORDER,
  [CHANNELS.QUEUE_UPDATE]: RESPONSE_SCHEMAS.QUEUE_UPDATE,
  [CHANNELS.UPLOAD_START]: RESPONSE_SCHEMAS.UPLOAD_START,
  [CHANNELS.UPLOAD_PAUSE]: RESPONSE_SCHEMAS.UPLOAD_PAUSE,
  [CHANNELS.UPLOAD_RESUME]: RESPONSE_SCHEMAS.UPLOAD_RESUME,
  [CHANNELS.UPLOAD_CANCEL]: RESPONSE_SCHEMAS.UPLOAD_CANCEL,
  [CHANNELS.METADATA_GET_CATEGORIES]: RESPONSE_SCHEMAS.METADATA_GET_CATEGORIES,
  [CHANNELS.METADATA_GET_PLAYLISTS]: RESPONSE_SCHEMAS.METADATA_GET_PLAYLISTS,
}

export const CHANNEL_EVENT_SCHEMAS = {
  [CHANNELS.UPLOAD_PROGRESS]: EVENT_SCHEMAS.UPLOAD_PROGRESS,
  [CHANNELS.UPLOAD_STATUS_CHANGED]: EVENT_SCHEMAS.UPLOAD_STATUS_CHANGED,
}

export { YOUTUBE_MANAGER_API_CONTRACT }
